<a href="https://colab.research.google.com/github/Neerajmn28/Data-science-assignments/blob/main/Hypothesis_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

## Question 1

In [ ]:
df=pd.read_csv('Cutlets.csv')

 Step 1
 Define hypothesis

Ho µ1 = µ2

Ha µ1 ≠ µ2

```
# This is formatted as code
```

In [ ]:
df

    Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [ ]:
data1= df.iloc[:,0]

In [ ]:
data2=df.iloc[:,1]

In [ ]:
data1

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [ ]:
data2

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

Checking for null values

In [ ]:
df.isnull().sum()

Unit A    0
Unit B    0
dtype: int64

Checking for Duplicate values

In [ ]:
df[df.duplicated()].shape

(0, 2)

 Checking the info

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes

In [ ]:
stats.ttest_ind(df[['Unit A']],df[['Unit B']])

Ttest_indResult(statistic=array([0.72286887]), pvalue=array([0.47223947]))

Compare P value with Alpha

Alpha= 0.5 and p value= 0.47

If P value = α 'We reject null hypothesis'

If P value ≠ α ' We accept null hypothesis'

So here the P value is more than alpha so we accept Null hypothesis.

## Question no 2

In [ ]:
df1=pd.read_csv('LabTAT.csv')

In [ ]:
df1

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [ ]:
df1.head()

   Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [ ]:
df1.tail()

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

Checking for null values

In [ ]:
df1.isnull().sum()

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [ ]:
stats.f_oneway(df1.iloc[:,0],df1.iloc[:,1],df1.iloc[:,2],df1.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

So here the alpha = 0.5
And the P value =  0.0

Here the p value < alpha So we reject Ho. So there is a significant difference between reports.

# Question no 3

In [ ]:
df2= pd.read_csv('BuyerRatio.csv')

In [ ]:
df2

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
df2.describe()

             East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

Defining

Ho: The variables are independent

Ha: The variables are dependent

In [ ]:
stats.chi2_contingency([df2['East'],df2['West'],df2['North'],df2['South']])

Chi2ContingencyResult(statistic=1.5959455386610577, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  442.23468701],
       [ 146.81287862, 1518.18712138],
       [ 131.11756787, 1355.88243213],
       [  72.30424052,  747.69575948]]))

In [ ]:
alpha= 0.05
p_value= 0.6603094907091882
if p_value < alpha:
    print('we reject the null hypothesis')
else:
    print('we fail to reject null hypothesis')

we fail to reject null hypothesis

## Question no 4

In [ ]:
df3=pd.read_csv('/content/Costomer+OrderForm.csv')

In [ ]:
df3

    Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

Checking for null values

In [ ]:
df3.isnull().sum()

Phillippines    0
Indonesia       0
Malta           0
India           0
dtype: int64

Ho: The variables are independent

Ha: The variables are dependent

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

In [ ]:
df3['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [ ]:
df3['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [ ]:
df3['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [ ]:
df3['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [ ]:
pd.DataFrame({'Country':['Phillippines','Indonsia','Malta','India'],
             'Error Free':[271,267,269,280],
             'Defective':[29,33,31,20]})

        Country  Error Free  Defective
0  Phillippines         271         29
1      Indonsia         267         33
2         Malta         269         31
3         India         280         20

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
stats.chi2_contingency([df3['India'].value_counts(),df3['Indonesia'].value_counts(),df3['Malta'].value_counts(),df3['Phillippines'].value_counts()])

Chi2ContingencyResult(statistic=3.8589606858203545, pvalue=0.2771020991233144, dof=3, expected_freq=array([[271.75,  28.25],
       [271.75,  28.25],
       [271.75,  28.25],
       [271.75,  28.25]]))

So, here the P value is > alpha,

so accept Null hypothesis.